### ISSUE TITLE
class MLP_Mixer miss use in forward causing model stored in cpu

### ISSUE THREAD

**Issue by lclkent** [lavish619/MLP-Mixer-PyTorch#1]
The model should be initialized in __init__ as bellow and inferred in forward
`layers = []`
`       for _ in range(self.num_mixers):`
`          layers.append(Mixer_Layer(self.num_patches,`
`                                   self.num_features,`
`                                 self.expansion_token,`
`                                 self.expansion_channel, `
`                                 self.dropout))`
`        self.model = nn.Sequential(*layers)`

**Comment by lavish619** [comment]
Thanks for pointing this out,  I haven't tested it on GPU initially. Now I have corrected it.
